'use client';

import { useRef, useState, type CSSProperties } from 'react';
import Link from 'next/link';
import { auralisDemo, type DemoStage } from '../../../src/data/auralis-demo';
import './demo.css';

type IconName = 'wave' | 'folder' | 'mic' | 'task' | 'spark' | 'settings' | 'help' | 'send' | 'check' | 'play' | 'refresh' | 'more' | 'chevron';

function Icon({ name, size = 16 }: { name: IconName; size?: number }) {
  const paths: Record<IconName, string> = {
    wave: 'M3 9.5c2.2-4.9 3.7 7 5.7 0s3.4-4.9 5.4 0 3.2 4.9 5.9 0', folder: 'M3 6.5h6l1.5 2H21v9.2a1.3 1.3 0 0 1-1.3 1.3H4.3A1.3 1.3 0 0 1 3 17.7V6.5Z', mic: 'M12 15.4a3.3 3.3 0 0 0 3.3-3.3V6.8a3.3 3.3 0 1 0-6.6 0v5.3a3.3 3.3 0 0 0 3.3 3.3Zm-5-3.2a5 5 0 0 0 10 0M12 17.2v3M9.4 20.2h5.2', task: 'M5 4.5h14v15H5zM8 8h8M8 12h8M8 16h5', spark: 'm12 3 1.2 5.8L19 10l-5.8 1.2L12 17l-1.2-5.8L5 10l5.8-1.2L12 3ZM19 16l.6 2.4L22 19l-2.4.6L19 22l-.6-2.4L16 19l2.4-.6L19 16Z', settings: 'M12 8.3a3.7 3.7 0 1 0 0 7.4 3.7 3.7 0 0 0 0-7.4Zm0-5.1 1 .3.6 2.2c.5.2 1 .4 1.4.8l2.2-.5.7.8-1 2c.3.4.6.9.8 1.4l2.1.7.1 1.1-1.9 1c0 .6-.1 1.1-.3 1.6l1.5 1.7-.5 1-2.2-.1c-.4.4-.8.7-1.3 1l-.1 2.2-1 .5-1.6-1.5c-.5.2-1 .3-1.6.3l-1.1 1.9-1.1-.1-.7-2.1c-.5-.2-1-.5-1.4-.8l-2 .9-.8-.7.5-2.2c-.3-.4-.6-.9-.8-1.4l-2.2-.6-.2-1.1 1.9-1c0-.6.1-1.1.3-1.6L4 7.8l.5-1 2.2.1c.4-.4.8-.7 1.3-1l.1-2.2 1-.5L10.7 5c.5-.2 1-.3 1.6-.3L12 3.2Z', help: 'M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Zm0-5v.1M9.8 9a2.3 2.3 0 1 1 3.6 1.9c-.9.6-1.4 1.1-1.4 2.1', send: 'm3 3 18 9-18 9 3.2-9L3 3Zm3.2 9h8.5', check: 'm5 12 4.3 4.3L19 6.8', play: 'm8 5 10 7-10 7V5Z', refresh: 'M20 11a8 8 0 0 0-14.8-3L3 11m0 0V5m0 6h6M4 13a8 8 0 0 0 14.8 3L21 13m0 0v6m0-6h-6', more: 'M5 12h.1M12 12h.1M19 12h.1', chevron: 'm8 10 4 4 4-4',
  };
  return <svg aria-hidden="true" className="auralis-icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d={paths[name]} /></svg>;
}

const stages: Array<{ id: DemoStage; label: string; detail: string }> = [
  { id: 'source', label: '准备解析', detail: '输入原文' }, { id: 'roles', label: '确认人物设定', detail: '编辑人物卡' }, { id: 'script', label: '确认广播剧台本', detail: '审阅初稿' }, { id: 'production', label: '逐句制作', detail: '试听与重生成' },
];
const stageHeadings: Record<DemoStage, { title: string; status: string }> = {
  source: { title: '准备解析', status: '等待小说原文' }, roles: { title: '确认人物设定', status: 'AI 已完成初步识别' }, script: { title: '确认广播剧台本', status: '初稿已出 · AI 审查通过' }, production: { title: '逐句制作', status: '4 个制作单元 · 3 个已就绪' },
};
const roleColors = ['#37c9c6', '#e39bca'];

export default function AuralisProjectDemoPage() {
  const [stage, setStage] = useState<DemoStage>('source');
  const [source, setSource] = useState('');
  const [instruction, setInstruction] = useState(auralisDemo.instruction);
  const [roles, setRoles] = useState(auralisDemo.roles.map((role) => ({ ...role })));
  const [toast, setToast] = useState('');
  const [busy, setBusy] = useState(false);
  const [revised, setRevised] = useState(false);
  const audioContext = useRef<AudioContext | null>(null);
  const activeOscillator = useRef<OscillatorNode | null>(null);
  const currentIndex = stages.findIndex((item) => item.id === stage);
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2600); };
  const transition = (nextStage: DemoStage, message: string) => { setBusy(true); window.setTimeout(() => { setBusy(false); setStage(nextStage); notify(message); }, 600); };
  const loadExample = () => { setSource(auralisDemo.sourceText); notify('已载入示例小说片段'); };
  const playTone = (frequency: number, number: string) => {
    activeOscillator.current?.stop();
    const AudioContextClass = window.AudioContext || (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
    if (!AudioContextClass) { notify('当前浏览器不支持试听'); return; }
    audioContext.current ??= new AudioContextClass();
    const oscillator = audioContext.current.createOscillator(); const gain = audioContext.current.createGain(); oscillator.type = 'sine'; oscillator.frequency.value = frequency;
    gain.gain.setValueAtTime(0.0001, audioContext.current.currentTime); gain.gain.exponentialRampToValueAtTime(0.12, audioContext.current.currentTime + 0.05); gain.gain.exponentialRampToValueAtTime(0.0001, audioContext.current.currentTime + 1.15);
    oscillator.connect(gain).connect(audioContext.current.destination); oscillator.start(); oscillator.stop(audioContext.current.currentTime + 1.2); activeOscillator.current = oscillator; notify(`正在试听第 ${number} 句 · 静态音频预览`);
  };
  const reset = () => { activeOscillator.current?.stop(); setSource(''); setStage('source'); setRevised(false); notify('已重置当前工作台'); };

  return <div className="auralis-app-shell">
    <aside className="auralis-app-sidebar">
      <Link href="/" prefetch={false} className="auralis-brand"><span className="auralis-brand-mark"><Icon name="wave" size={22} /></span><span><strong>Auralis</strong><small>SONIC DRAMA STUDIO</small></span></Link>
      <div className="auralis-side-group"><span className="auralis-side-label">WORKSPACE</span><button className="auralis-side-item selected" type="button"><Icon name="folder" /><span>项目</span><b>1</b></button><button className="auralis-side-item" type="button" onClick={() => notify('音色管理在完整应用中使用')}><Icon name="mic" /><span>音色</span></button><button className="auralis-side-item" type="button" onClick={() => notify('任务中心在完整应用中使用')}><Icon name="task" /><span>任务</span></button></div>
      <div className="auralis-side-group side-tools"><span className="auralis-side-label">UTILITIES</span><button className="auralis-side-item" type="button" onClick={() => notify('静态 Demo 不连接外部提示词库')}><Icon name="spark" /><span>提示词</span></button><button className="auralis-side-item" type="button" onClick={() => notify('这是静态体验版，设置不会被保存')}><Icon name="settings" /><span>设置</span></button></div>
      <div className="auralis-side-bottom"><button className="auralis-side-item" type="button" onClick={() => notify('帮助中心在完整应用中使用')}><Icon name="help" /><span>帮助</span></button><div className="auralis-user"><span>R</span><div><strong>Rheeh</strong><small>静态体验账户</small></div><Icon name="more" size={17} /></div></div>
    </aside>
    <main className="auralis-app-main">
      <header className="auralis-workspace-bar"><div className="auralis-breadcrumb"><span>项目</span><i>/</i><strong>{auralisDemo.project.title}</strong><em>DEMO</em></div><div className="auralis-bar-actions"><span className="auralis-local-status"><i /> 本地自动保存</span><Link href="/" prefetch={false} className="auralis-portfolio-link">返回 Portfolio</Link></div></header>
      <div className="auralis-workspace-grid">
        <section className="auralis-conversation-panel" aria-label="Auralis 对话与输入"><div className="auralis-conversation-scroll"><div className="auralis-project-head"><div><span className="auralis-kicker">项目工作台</span><h1>{auralisDemo.project.title}</h1><p>{auralisDemo.project.caption}</p></div><button className="auralis-icon-button" type="button" aria-label="更多项目操作" onClick={() => notify('项目操作菜单在完整应用中可用')}><Icon name="more" /></button></div><div className="auralis-assistant-message"><div className="auralis-avatar"><Icon name="spark" size={15} /></div><div><strong>一个页面完成广播剧制作</strong><p>我会先解析小说并生成主要角色身份卡；你确认人物后生成台本，满意后逐句绑定音色并生成音频。</p></div></div>{stage !== 'source' && <div className="auralis-chat-note"><span><Icon name="check" size={14} /></span><p>{stage === 'roles' ? '原文解析完成，已识别 2 个主要人物。' : stage === 'script' ? '人物设定已确认，台本初稿已生成。' : '台本已确认，已建立逐句制作单元。'}</p></div>}<div className="auralis-demo-note"><span>STATIC DEMO</span><p>以下操作模拟真实工作流，文本只保留在当前浏览器页面。</p></div></div><div className="auralis-source-composer">{stage === 'source' ? <><div className="auralis-composer-title"><strong>新建制作任务</strong><span>{source.trim().length} / 5000</span></div><input aria-label="项目标题" value="雨夜来信" readOnly /><textarea aria-label="小说原文" rows={6} value={source} onChange={(event) => setSource(event.target.value)} placeholder="把小说原文粘贴到这里……" /><div className="auralis-composer-foot"><button type="button" className="auralis-text-button" onClick={loadExample}>载入示例</button><span>{instruction ? '已添加改编要求' : '可添加改编要求'}</span></div><div className="auralis-instruction-row"><input aria-label="改编要求" value={instruction} onChange={(event) => setInstruction(event.target.value)} placeholder="例如：旁白克制，用环境声推进" /><button type="button" aria-label="开始解析" className="auralis-send-button" disabled={busy} onClick={() => source.trim().length < 20 ? notify('请先输入至少 20 个字，或载入示例') : transition('roles', '解析完成：已识别人物、关系和场景')}><Icon name="send" size={17} /></button></div></> : <><div className="auralis-composer-title"><strong>{stage === 'roles' ? '确认人物后继续' : stage === 'script' ? '确认台本后继续' : '制作已进入逐句阶段'}</strong><span>工作流 {currentIndex + 1} / 4</span></div><div className="auralis-stage-prompt">{stage === 'roles' ? '检查人物身份卡和说话方式，确认后生成台本。' : stage === 'script' ? '可以先让 AI 减少旁白，也可以直接确认当前台本。' : '点击右侧播放按钮试听，或对单句进行重生成。'}</div><button className="auralis-composer-action" type="button" disabled={busy} onClick={() => stage === 'roles' ? transition('script', '台本初稿已生成，AI 审查通过') : stage === 'script' ? transition('production', '已建立逐句制作单元') : notify('可以在右侧逐句试听')}>{busy ? '处理中…' : stage === 'roles' ? '确认人物并生成台本' : stage === 'script' ? '台本满意，进入逐句制作' : '继续试听右侧音频'}<Icon name="send" size={15} /></button></>}</div></section>
        <section className="auralis-result-panel" aria-label="Auralis 制作结果"><div className="auralis-result-head"><div className="auralis-stage-dots">{stages.map((item, index) => <button key={item.id} type="button" className={index === currentIndex ? 'active' : index < currentIndex ? 'done' : ''} onClick={() => index <= currentIndex && setStage(item.id)}><span>{index < currentIndex ? <Icon name="check" size={12} /> : index + 1}</span>{item.label}</button>)}</div><div className="auralis-result-tools"><span>{stageHeadings[stage].status}</span><button type="button" aria-label="刷新工作区" onClick={() => notify('静态工作台状态已刷新')}><Icon name="refresh" size={15} /></button></div></div><div className="auralis-result-scroll">
          {stage === 'source' && <div className="auralis-empty-state"><div className="auralis-empty-icon"><Icon name="wave" size={30} /></div><h2>等待小说原文</h2><p>从左侧输入一段故事，Auralis 会将它拆成<br />人物、台本和可试听的声音单元。</p><button type="button" className="auralis-outline-button" onClick={loadExample}>使用示例片段</button></div>}
          {stage === 'roles' && <div className="auralis-result-content"><div className="auralis-result-title"><div><span className="auralis-kicker">ROLE DRAFT</span><h2>主要人物身份卡</h2><p>AI 从原文中识别出以下人物，请确认说话方式。</p></div><span className="auralis-count-badge">2 个角色</span></div><div className="auralis-role-list">{roles.map((role, index) => <article className="auralis-role-card" key={role.name} style={{ '--role-color': roleColors[index] } as CSSProperties}><div className="auralis-role-card-head"><span className="auralis-role-avatar">{role.avatar}</span><div><strong>{role.name}</strong><small>{role.role}</small></div><button type="button" aria-label={`编辑${role.name}`} onClick={() => notify('角色信息可在此处编辑')}><Icon name="more" size={15} /></button></div><div className="auralis-role-fields"><label>身份描述<input value={role.role} onChange={(event) => setRoles(roles.map((item, itemIndex) => itemIndex === index ? { ...item, role: event.target.value } : item))} /></label><label>说话方式<input value={role.voice} onChange={(event) => setRoles(roles.map((item, itemIndex) => itemIndex === index ? { ...item, voice: event.target.value } : item))} /></label></div><div className="auralis-role-voice"><Icon name="mic" size={14} /><span>默认音色 · {index === 0 ? '低沉叙事' : '清晰对话'}</span><button type="button" onClick={() => notify(`${role.name} 的音色预览已准备`)}>试听</button></div></article>)}</div><div className="auralis-confirm-strip"><span><Icon name="check" size={15} /> 可编辑中间结果</span><button type="button" className="auralis-primary-button" onClick={() => transition('script', '台本初稿已生成，AI 审查通过')} disabled={busy}>{busy ? '生成中…' : '确认人物并生成台本'}<Icon name="send" size={15} /></button></div></div>}
          {stage === 'script' && <div className="auralis-result-content"><div className="auralis-result-title"><div><span className="auralis-kicker">SCRIPT DRAFT · AI REVIEW PASSED</span><h2>广播剧台本初稿</h2><p>场景已拆分，音效和对白可以在制作前继续修改。</p></div><span className="auralis-count-badge success">审查通过</span></div><div className="auralis-review-summary"><Icon name="spark" size={17} /><div><strong>AI 审查结果</strong><p>对白自然度良好 · 旁白占比 {revised ? '12' : '18'}% · 音效提示 3 条</p></div><button type="button" onClick={() => { setRevised(true); notify('已模拟返修：减少一条旁白'); }}>{revised ? '已减少旁白' : '减少旁白'}</button></div><div className="auralis-script-draft"><div className="auralis-scene-bar"><span>SCENE 01</span><strong>楼道 · 重逢前夜</strong><Icon name="chevron" size={15} /></div>{auralisDemo.script.map((line, index) => <div className="auralis-script-line" key={`${line.text}-${index}`}><span className={`auralis-script-tag ${line.kind}`}>{line.type}</span><p>{revised && line.kind === 'narration' ? '雨声压过楼道的灯，林默站在门外。' : line.text}</p><button type="button" aria-label="编辑台本句子" onClick={() => notify('台本句子可在此处编辑')}><Icon name="more" size={15} /></button></div>)}</div><div className="auralis-confirm-strip"><span>初稿可编辑 · 共 4 句</span><button type="button" className="auralis-primary-button" onClick={() => transition('production', '已建立逐句制作单元')} disabled={busy}>{busy ? '建立中…' : '台本满意，进入逐句制作'}<Icon name="send" size={15} /></button></div></div>}
          {stage === 'production' && <div className="auralis-result-content"><div className="auralis-result-title production-title"><div><span className="auralis-kicker">PRODUCTION SCRIPT</span><h2>逐句制作时间线</h2><p>每句独立试听或重生成，保留可逆的编辑空间。</p></div><span className="auralis-count-badge success">3 / 4 就绪</span></div><details className="auralis-source-fold"><summary><span>原文参考</span><Icon name="chevron" size={15} /></summary><p>{auralisDemo.sourceText}</p></details><div className="auralis-scene-block"><div className="auralis-scene-bar"><div><span>SCENE 01 / RAINY NIGHT</span><strong>楼道 · 重逢前夜</strong></div><button type="button" aria-label="场景操作" onClick={() => notify('场景操作菜单在完整应用中可用')}><Icon name="more" size={16} /></button></div><div className="auralis-timeline">{auralisDemo.audioLines.map((line, index) => <article className="auralis-production-line" key={line.number} style={{ '--role-color': line.speaker === '旁白' ? '#8e9aaa' : line.speaker === '音效' ? '#e5a34d' : roleColors[index - 2] } as CSSProperties}><div className="auralis-timeline-dot"><span>{index + 1}</span></div><div className="auralis-line-body"><div className="auralis-line-meta"><strong>{line.speaker}</strong><span>{line.speaker === '音效' ? '环境声' : '默认音色'}</span><button type="button" aria-label="句子操作" onClick={() => notify(`第 ${line.number} 句操作菜单已打开`)}><Icon name="more" size={14} /></button></div><p>{line.text}</p><div className="auralis-audio-strip"><button type="button" className="auralis-round-play" aria-label={`播放第 ${line.number} 句`} onClick={() => playTone(line.frequency, line.number)}><Icon name="play" size={13} /></button><div className="auralis-waveform" aria-hidden="true">{Array.from({ length: 32 }, (_, waveIndex) => <i key={waveIndex} style={{ height: `${7 + ((waveIndex * 17 + index * 11) % 18)}px` }} />)}</div><span>00:0{index + 2}</span><button type="button" className="auralis-regenerate" onClick={() => notify(`第 ${line.number} 句已生成新的试听版本`)}><Icon name="refresh" size={13} /> 重生成</button></div></div></article>)}</div></div><div className="auralis-master-player"><button type="button" className="auralis-master-play" onClick={() => playTone(294, '全部')}><Icon name="play" size={13} /></button><div><strong>场景预览</strong><span>4 句 · 00:18</span></div><div className="auralis-master-wave">{Array.from({ length: 44 }, (_, index) => <i key={index} style={{ height: `${8 + ((index * 13) % 18)}px` }} />)}</div><button type="button" className="auralis-export-button" onClick={() => notify('静态 Demo 不生成文件，完整应用支持导出')}>导出音频</button></div><div className="auralis-confirm-strip"><span>静态试听 · 音频由浏览器合成</span><button type="button" className="auralis-outline-button" onClick={reset}><Icon name="refresh" size={14} /> 重新体验</button></div></div>}
        </div></section>
      </div>
    </main>
    {toast && <div className="auralis-toast" role="status" aria-live="polite">{toast}</div>}
  </div>;
}
